### ISSUE TITLE
Indicator options

### ISSUE THREAD

**Issue by PSTrophy** [beatmasterRS/skin.arctic.zephyr.mod#106]
I was just wondering if it's possible to change the option to turn off and on all indicators into a submenu where we can toggle individual indicators on or off? For example unwatched, watched, new, hot, ratings and resume. I'd settle for just unwatched though. Also if the menu is doable the next aired, IMDb top 250, my rating and RT and MC rating toggles could be moved from media flags into there since they aren't media flags and more indicators IMO and would give people more flexibility over the skin and gives you guys a dedicated section to add extra options at a later date. Thanks

**Comment by fabricionaweb** [comment]
Can @beatmasterRS confirm which indicators we have?

- Watched (check icon)
- Unwatched (ball icon)
- In Progress (half ball icon)
- New (the burn icon)

![image](https://user-images.githubusercontent.com/15933/110243834-00a92e80-7f54-11eb-970d-5355fecc8658.png)

Is that all?

**Comment by PSTrophy** [comment]
I would categorise trakt and RT/MC ratings, IMDb top 250, next aired as indicators as well but I think that's all we have for now.

**Comment by fabricionaweb** [comment]
I personally dont agree to move `RT/MC, IMDB and Next Aired` out from media flags section... Because to me makes sense as it is. You will always see they together in the same spot, in the media flags spot.
I agree when you think about the `right semantic meaning` this seems wrong... but to me, personally, it makes sense when you think about the user experience... As user, I can easier found it as media-flag...

I'm thinking in add + 4 items bellow the `Indicators` option on `Furniture` settings, will only be enable when `Indicators` are enable.

I need to know what @beatmasterRS think about it, if he have a better ideia or something...

**Comment by beatmasterRS** [comment]
I am with you @fabricionaweb 

@PSTrophy I don't want there to be a mass of options at the end, like in Titan. Options and dialogs as simple as possible would be cool. :)

I'll take a closer look at the expressions when I get home from work. For now it looks good. Maybe we can exclude all expressions in a new file later, when you have all expressions you like. Then the includes.xml would be a bit clearer :) with its 3000 lines of code :D

**Comment by PSTrophy** [comment]
When it comes to ratings and things like that I personally don't go straight to media flags to find the toggle but I'm probably in the minority so fair enough. I agree that having those things in the media flags section makes no sense as technically they aren't media flags but see your thinking but sticking everything in one section seems like a recipe for confusion later down the line as more things get added and media flags becomes the default area to stick everything when logically it makes no sense and becomes bloated as a result. I guess it's something to think about at a later date :)

**Comment by fabricionaweb** [comment]
I see your point, you're right, we need to be careful...
