### ISSUE TITLE
[Query]No results found when clicked on cast

### ISSUE THREAD

**Issue by onlytanmoy** [beatmasterRS/skin.arctic.zephyr.mod#115]
Hiya, first things first, many thanks for this beautiful skin. Just now installed it on Kodi 19 running on my Shield pro.
I have used Arctic Horizon, AZ2, Aura Mod extensively with Kodi 18, so got the idea of setting up widgets etc.
Please see the video recording, I currently got the widget pointed to Seren > Trakt> My Movie List, when I click on a cast, it says 'no results found'.
https://imgur.com/a/t4MpqxR
I am expecting it to display the movies the cast is associated with, how can I fix this please?

**Comment by beatmasterRS** [comment]
The cast list is only filled, if content (movies/actors/...) has been added to the library.

**Comment by onlytanmoy** [comment]
> The cast list is only filled, if content (movies/actors/...) has been added to the library.

Thanks for your response...I am not using local library in Kodi, just stream online via Seren, Fen etc. So in that case this feature won't work for me right?

**Comment by beatmasterRS** [comment]
yes, exactly. :)

**Comment by onlytanmoy** [comment]
> yes, exactly. :)

Ok 😊 thanks for the clarification. 
Qq- is there a way to display the year of the movie in the Home screen widget beside the movie name so like Raya and the last dragon (2021)?

**Comment by beatmasterRS** [comment]
Which one of the homescreen widget layouts du you mean?

**Comment by onlytanmoy** [comment]
> Which one of the homescreen widget layouts du you mean?
'Vertical Multi-Widgets' home menu style
I meant like below, I have manually added the year of the movie
![Kodi_20210309_091848](https://user-images.githubusercontent.com/48493659/110448504-2b60c780-80b9-11eb-908d-e8e8ad96eb8c.png)

**Comment by beatmasterRS** [comment]
Unfortunately you would have to add this yourself, because I can't integrate it like this, as it then sometimes results in the year being displayed twice when fullscreen widgets are used.

- open 1080i/Includes_Home.xml
- after line 5614 insert the following code

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/blob/1353affa57c240611bc6de97edbe154f7db7cc6d/1080i/Includes_Home.xml#L5615-L5626

- save the file
- reload the skin or restart kodi for changes to take effect

Alternatively you can also download the skin from this branch

https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/label-testing.zip

I'll take another look at this and see if I can find a solution to integrate this permanently into the skin. :)

**Comment by onlytanmoy** [comment]
@beatmasterRS apologies for the late response, was pretty held up in my day job today until now. Really appreciate the workaround you have provided me. I reported one feature request on windowed mode trailer earlier today which you have already labelled as Kodi 19 I can see :) I will be putting forth one more in some time now. Thanks mate.
