### ISSUE TITLE
Some PVR channel logos not displayed properly in OSD

### ISSUE THREAD

**Issue by zeddgb** [beatmasterRS/skin.arctic.zephyr.mod#238]
If you set the below logo for a channel and bring up the OSD, the bottom of it will be cut off and the top will extend beyond the bounds of the OSD. This only occurs with the Standard OSD.

![example](https://user-images.githubusercontent.com/11862293/119220541-61491000-bb2e-11eb-9228-aaff018cf30d.png)

**Comment by beatmasterRS** [comment]
Please provide a screenshot if this issue, thanks.

**Comment by zeddgb** [comment]
Here is a screenshot that shows this issue and also issue #236 as a bonus:

![screenshot](https://user-images.githubusercontent.com/11862293/119222853-b8a0ad80-bb39-11eb-9e1c-161297518b8c.jpg)

**Comment by beatmasterRS** [comment]
I think it will be so that the channel logos will also get a square background with border, because otherwise it can sometimes come to unsightly behavior.

Bevore:

![screenshot01047](https://user-images.githubusercontent.com/3855273/119237004-d4588380-bb3a-11eb-857f-2c1df9456317.png)

After:

![screenshot01048](https://user-images.githubusercontent.com/3855273/119237007-dc182800-bb3a-11eb-9148-ffeedfad4d07.png)

**Comment by beatmasterRS** [comment]
https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/issues-pvr-fix-testing.zip

**Comment by zeddgb** [comment]
Thanks, just tested that build and it does solve the problem.

Knowing absolutely nothing about the Kodi skinning engine, is it not possible to simply scale the width/height (whichever is greater) of an image to keep it within the bounds of the OSD?

**Comment by beatmasterRS** [comment]
That would be an absolutely cool feature, but the Kodi skinning engine doesn't support that.
