### ISSUE TITLE
Poster Flix V2: Clearlogo cannot be disabled for episodes

### ISSUE THREAD

**Issue by micheyll** [beatmasterRS/skin.arctic.zephyr.mod#629]
After release 1.1.61, the clearlogos cannot be disabled for seasons/episodes independently from the series view when using Poster Flix V2.

If the ”clearlogo instead of title” setting is disabled in the episodes view, it gets disabled for the whole library. Seasons view is missing this setting altogether.

**Comment by beatmasterRS** [comment]
Thanks for reporting. This has allready been fixed in the latest master. Commit: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/commit/cd28fa083606548b57993189c27ac28ae486395f

If you would like to test the latest version, please download the zip file: https://github.com/beatmasterRS/skin.arctic.zephyr.mod/archive/refs/heads/master.zip

**Comment by micheyll** [comment]
Thank you so much. :)
